#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cycle1/Allclean
cycle1/Allrun

cycle1c/Allclean
cycle1c/Allrun

cycle2/Allclean
cycle2/Allrun

cycle2c/Allclean
cycle2c/Allrun




#------------------------------------------------------------------------------
