#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------


runApplication blockMesh

runApplication checkMesh

runApplication topoSet

#runApplication createZones

runApplication createPatch

runApplication $(getApplication)

#pyFoamPlotRunner.py $(getApplication)

#------------------------------------------------------------------------------
