#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------


runApplication blockMesh

runApplication topoSet

runApplication createPatch -overwrite

runApplication checkMesh

runApplication $(getApplication)

#pyFoamPlotRunner.py $(getApplication)

#------------------------------------------------------------------------------
