#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=$(getApplication)

runApplication blockMesh

runApplication checkMesh

runApplication topoSet

runApplication createPatch -overwrite

runApplication $application

#------------------------------------------------------------------------------
