#!/bin/sh
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------
cd tundishFlow2D
cleanCase
cd ../
#------------------------------------------------------------------------------
cd tundishScalar2D
cleanCase
cd ../